pipeline {
    agent any
    stages {
       stage('Checkout Code') { 
             git 'https://github.com/sandeep2523/multi-stage.git'
        }
        stage ('DOCKER Login') {
            steps {
                sh 'docker login -u="sandeep2523" -p="Sandeep@2523"
            }
        }
        
        stage ('DOCKER BUILD') {
            when {
                branch 'master'
            }
            steps {
                sh 'docker build -t newsandeep /maven/Dockerfile .'
            }
        }
        stage ('DOCKER run and deploy') {
            steps {
                sh 'docker run -it -d -p 8070:8080 --name sandeep-conatiner newsandeep'
            }
        }
       
    }  
    
}
