pipeline {
    agent any
    stages {
       stage('Checkout Code') {
           steps {
             git 'https://github.com/sandeep2523/multi-stage.git'
        }
       }
        stage ('DOCKER Login') {
           steps {
               sh 'docker login --username="sandeep2523" --password-stdin="Sandeep@2523"'
            }
        }
        
        stage ('DOCKER BUILD') {
            steps {
                sh 'docker build -t newsandeep /maven/Dockerfile .'
            }
        }
        stage ('DOCKER PUSH') {
            steps {
                sh 'docker tag newsandeep sandeep2523/newsandeep:1.0'
                sh 'docker push sandeep2523/newsandeep:1.0'
            }
        }
        stage ('DOCKER run and deploy') {
            steps {
                sh 'docker run -it -d -p 8070:8080 --name sandeep-conatiner newsandeep'
            }
        }
       
    }  
    
}
